-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 16:35:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema technovation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technovation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technovation` DEFAULT CHARACTER SET utf8mb3 ;
USE `technovation` ;

-- -----------------------------------------------------
-- Table `technovation`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `Descriotion` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(100) NULL DEFAULT NULL,
  `Address` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`business` (
  `id_business` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Online_OnSite` VARCHAR(100) NULL DEFAULT NULL,
  `Description` VARCHAR(1000) NULL DEFAULT NULL,
  `Photo` VARCHAR(1000) NULL DEFAULT NULL,
  `category_id_category` INT NOT NULL,
  `location_id_location` INT NOT NULL,
  PRIMARY KEY (`id_business`),
  INDEX `fk_business_category1_idx` (`category_id_category` ASC),
  INDEX `fk_business_location1_idx` (`location_id_location` ASC),
  CONSTRAINT `fk_business_category1`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `technovation`.`category` (`id_category`),
  CONSTRAINT `fk_business_location1`
    FOREIGN KEY (`location_id_location`)
    REFERENCES `technovation`.`location` (`id_location`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`phone_number` (
  `id_number` INT NOT NULL AUTO_INCREMENT,
  `Number` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(100) NULL DEFAULT NULL,
  `Lname` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Password` VARCHAR(3000) NULL DEFAULT NULL,
  `Profile_Photo` VARCHAR(1000) NULL DEFAULT NULL,
  `is_business_user` TINYINT NOT NULL,
  `business_id_business` INT NULL DEFAULT NULL,
  `phone_number_id_number` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_business_idx` (`business_id_business` ASC),
  INDEX `fk_user_phone_number1_idx` (`phone_number_id_number` ASC),
  CONSTRAINT `fk_user_business`
    FOREIGN KEY (`business_id_business`)
    REFERENCES `technovation`.`business` (`id_business`),
  CONSTRAINT `fk_user_phone_number1`
    FOREIGN KEY (`phone_number_id_number`)
    REFERENCES `technovation`.`phone_number` (`id_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
