-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 16:23:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema technovation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technovation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technovation` DEFAULT CHARACTER SET utf8mb3 ;
USE `technovation` ;

-- -----------------------------------------------------
-- Table `technovation`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descriotion` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `online_or_onsite` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `photo` VARCHAR(1000) NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_business_category1_idx` (`category_id` ASC),
  INDEX `fk_business_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_business_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `technovation`.`category` (`id`),
  CONSTRAINT `fk_business_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `technovation`.`location` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`phone_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovation`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovation`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(3000) NULL DEFAULT NULL,
  `profile_photo` VARCHAR(1000) NULL DEFAULT NULL,
  `is_business_user` TINYINT NOT NULL,
  `business_id` INT NULL DEFAULT NULL,
  `phone_number_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_business_idx` (`business_id` ASC),
  INDEX `fk_user_phone_number1_idx` (`phone_number_id` ASC),
  CONSTRAINT `fk_user_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `technovation`.`business` (`id`),
  CONSTRAINT `fk_user_phone_number1`
    FOREIGN KEY (`phone_number_id`)
    REFERENCES `technovation`.`phone_number` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
