-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 09:20:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Technovation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Technovation
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `Technovation` DEFAULT CHARACTER SET utf8 ;
USE `Technovation` ;

-- -----------------------------------------------------
-- Table `Technovation`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovation`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `Descriotion` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Technovation`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovation`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(100) NULL,
  `Address` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Technovation`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovation`.`business` (
  `id_business` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `Online_OnSite` VARCHAR(100) NULL,
  `Description` VARCHAR(1000) NULL,
  `category_id_category` INT NOT NULL,
  `location_id_location` INT NOT NULL,
  PRIMARY KEY (`id_business`),
  INDEX `fk_business_category1_idx` (`category_id_category` ASC),
  INDEX `fk_business_location1_idx` (`location_id_location` ASC),
  CONSTRAINT `fk_business_category1`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `Technovation`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_location1`
    FOREIGN KEY (`location_id_location`)
    REFERENCES `Technovation`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Technovation`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovation`.`phone_number` (
  `id_number` INT NOT NULL AUTO_INCREMENT,
  `Number` VARCHAR(100) NULL,
  PRIMARY KEY (`id_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Technovation`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Technovation`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `Fname` VARCHAR(100) NULL,
  `Lname` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NULL,
  `Password` VARCHAR(3000) NULL,
  `business_id_business` INT NOT NULL,
  `phone_number_id_number` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_business_idx` (`business_id_business` ASC),
  INDEX `fk_user_phone_number1_idx` (`phone_number_id_number` ASC),
  CONSTRAINT `fk_user_business`
    FOREIGN KEY (`business_id_business`)
    REFERENCES `Technovation`.`business` (`id_business`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_phone_number1`
    FOREIGN KEY (`phone_number_id_number`)
    REFERENCES `Technovation`.`phone_number` (`id_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
